# Generated by Django 4.1.3 on 2022-11-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bouns',
            field=models.IntegerField(),
        ),
    ]
