# Generated by Django 4.1.3 on 2022-11-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_employee_bouns'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depertment',
            new_name='Department',
        ),
    ]
