# Generated by Django 4.1.3 on 2022-11-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_rename_depertment_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bouns',
            new_name='bonus',
        ),
    ]
